In [1]:
import numpy as np


In [15]:
m = open('input/dataday5.txt','r').readlines()[0].rstrip('\n').split('->')
a,b = [tuple(map(int,x.strip().split(','))) for x in m]
m

['593,10 ', ' 593,98']

In [16]:
b

(593, 98)

In [7]:
import numpy as np
a = np.array([[1,2,3],[2,3,2]])
(a==2).sum()

3

In [11]:
import numpy as np

def get_lines():
    with open('input/dataday5.txt','r') as f:
        lines = f.readlines()
        v1 = []
        v2 = []
        max_x = 0
        max_y = 0
        for i,line in enumerate(lines):
            m = line.rstrip('\n').split('->')
            a,b = [list(map(int,x.strip().split(','))) for x in m]
            a = np.array(a)
            b = np.array(b)
            v1.append(a)
            v2.append(b)
            max_x = max([max_x,a[0],b[0]])
            max_y = max([max_y,a[1],b[1]])
    v1 = np.stack(v1)
    v2 = np.stack(v2)
    return v1,v2,max_x,max_y

def setup_grid(v1,v2,max_x,max_y):
    grid = np.zeros(shape = (max_x,max_y))
    for s,e in zip(v1,v2):
        if s[0] == e[0]:
            grid[s[0],s[1]:e[1]+1] += 1
        elif s[1] == e[1]:
            grid[s[0]:e[0],s[1]+1] += 1
    return grid

def main():
    v1,v2,max_x,max_y = get_lines()
    
    grid = setup_grid(v1,v2,max_x,max_y)
    nbr_of2s = (grid >= 2).sum()
    print(f'Puzzle 1, number of 2 line intersections: {nbr_of2s}')
    return v1,v2,grid,nbr_of2s


In [13]:
v1,v2,grid,nbr_of2s = main()

Puzzle 1, number of 2 line intersections: 1885


In [29]:
p = True
for s,e in zip(v1,v2):
    if p:
        print(s[1])
        print(e[1])
        p = False

10
98


In [66]:
a[:,0] += 1 
a

array([[ 4, 11,  9],
       [ 5, 24, 14]])

In [1]:
d = list(map(int,open('input/dataday6.txt','r').readlines()[0].split(',')))
# d

In [16]:
a = '16,1,2,0,4,2,7,1,2,14'
a = list(map(int,a.split(',')))
import numpy as np 
np.median(a)

2.0

In [13]:
data =  list(map(int,open('input/dataday7.txt','r').readlines()[0].split(',')))
max(data)

1927

In [4]:
open('input/dataday8.txt','r').readlines()[0].split('|')[-1].strip().strip('\n')

'dfbae be gdafe gcefab'

In [17]:
from day8 import decode,solve2
nums = 'acedgfb cdfbe gcdfa fbcad dab cefabd cdfgeb eafb cagedb ab'.split(' ')
outs = 'cdfeb fcadb cdfeb cdbaf'.split(' ')
dec = decode(nums)
inputs = [nums,nums]
outputs = [outs,outs]
s = solve2(inputs,outputs)
s/2

['acedgfb', 'cdfbe', 'gcdfa', 'fbcad', 'dab', 'cefabd', 'cdfgeb', 'eafb', 'cagedb', 'ab']
{'acedgfb': 8, 'dab': 7, 'eafb': 4, 'ab': 1, 'cdfbe': 5, 'gcdfa': 2, 'fbcad': 3, 'cefabd': 0, 'cdfgeb': 6, 'cagedb': 0}
['acedgfb', 'cdfbe', 'gcdfa', 'fbcad', 'dab', 'cefabd', 'cdfgeb', 'eafb', 'cagedb', 'ab']
{'acedgfb': 8, 'dab': 7, 'eafb': 4, 'ab': 1, 'cdfbe': 5, 'gcdfa': 2, 'fbcad': 3, 'cefabd': 0, 'cdfgeb': 6, 'cagedb': 0}
['acedgfb', 'cdfbe', 'gcdfa', 'fbcad', 'dab', 'cefabd', 'cdfgeb', 'eafb', 'cagedb', 'ab']
{'acedgfb': 8, 'dab': 7, 'eafb': 4, 'ab': 1, 'cdfbe': 5, 'gcdfa': 2, 'fbcad': 3, 'cefabd': 0, 'cdfgeb': 6, 'cagedb': 0}


5353.0

In [20]:
corr = {'acedgfb': 8,
    'cdfbe': 5,
    'gcdfa': 2,
    'fbcad': 3,
    'dab': 7,
    'cefabd': 9,
    'cdfgeb': 6,
    'eafb': 4,
    'cagedb': 0,
    'ab': 1}
for a in corr.keys():
    print(corr[a] == dec[a])
    print(a)
print(len(corr.keys()))
print(len(dec.keys()))


True
acedgfb
True
cdfbe
True
gcdfa
True
fbcad
True
dab
False
cefabd
True
cdfgeb
True
eafb
True
cagedb
True
ab
10
10


In [1]:
open('input/dataday9.txt').readlines()[0]

'9997656789876543234567989101298998743219853135678978901239999876543422349134989891012932398767323567\n'

In [5]:
data = [[int(s) for s in x.rstrip('\n')] for x in open('input/dataday11.txt','r').readlines()]
data

[[1, 4, 4, 3, 5, 8, 2, 1, 4, 8],
 [6, 5, 5, 3, 7, 3, 4, 8, 5, 1],
 [1, 4, 5, 1, 7, 4, 1, 2, 4, 6],
 [8, 8, 3, 5, 2, 1, 8, 8, 6, 4],
 [1, 6, 6, 2, 3, 1, 7, 2, 6, 2],
 [1, 7, 3, 1, 6, 5, 6, 6, 2, 3],
 [1, 1, 2, 8, 1, 7, 8, 3, 6, 7],
 [5, 8, 4, 2, 3, 5, 1, 6, 6, 5],
 [6, 6, 7, 7, 3, 2, 6, 8, 4, 3],
 [7, 3, 8, 1, 4, 3, 3, 2, 6, 7]]

In [7]:
import numpy as np
data = np.array(data)
data += 1
data


array([[2, 5, 5, 4, 6, 9, 3, 2, 5, 9],
       [7, 6, 6, 4, 8, 4, 5, 9, 6, 2],
       [2, 5, 6, 2, 8, 5, 2, 3, 5, 7],
       [9, 9, 4, 6, 3, 2, 9, 9, 7, 5],
       [2, 7, 7, 3, 4, 2, 8, 3, 7, 3],
       [2, 8, 4, 2, 7, 6, 7, 7, 3, 4],
       [2, 2, 3, 9, 2, 8, 9, 4, 7, 8],
       [6, 9, 5, 3, 4, 6, 2, 7, 7, 6],
       [7, 7, 8, 8, 4, 3, 7, 9, 5, 4],
       [8, 4, 9, 2, 5, 4, 4, 3, 7, 8]])

In [23]:
flashed = np.zeros(shape = data.shape)
flashed[data>7] = 1
flashed



array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 1.]])

In [19]:
len(a[0])

0

In [44]:
data[0,1] = 0
data[0,0] = 0
print(data)
print((data==0).sum())

[[ 0  0 44 43 45 48 42  1 44 48]
 [46 45 45 43 47 43 44 48 45  1]
 [ 1 44 45  1 47 44  1 42 44 46]
 [48 48 43 45 42  1 48 48 46 44]
 [ 1 46 46 42 43  1 47 42 46 42]
 [ 1 47 43  1 46 45 46 46 42 43]
 [ 1  1 42 48  1 47 48 43 46 47]
 [45 48 44 42 43 45  1 46 46 45]
 [46 46 47 47 43 42 46 48 44 43]
 [47 43 48  1 44 43 43 42 46 47]]
2


In [32]:
def make_step(data,have_flashed=[]):
    data += 1
    data[data>9] = 0
    flashers = np.where(data==0)
    if len(flashers) >0:
        have_flashed += [[r,c] for r,c in zip(flashers[0],flashers[1]) if [r,c] not in have_flashed]
    
    